[package]
name = "fix_frigate_img"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
actix-cors = "0.7.0"
actix-files = "0.6.6"
actix-web = "4.9.0"
env_logger = "0.11.5"
log = "0.4.22"
reqwest = "0.12.8"
tokio = { version = "1.41.0", features = ["full"] }
